const input=document.getElementById('urlInput'), button=document.getElementById('checkButton'), status=document.getElementById('status'), domain=document.getElementById('domain');
const resultBox=document.getElementById('result'), verdict=document.getElementById('verdict'), score=document.getElementById('score'), reasons=document.getElementById('reasons'), limitation=document.getElementById('limitation');
function setStatus(text,state='idle'){status.textContent=text;status.dataset.state=state;}
function updateDomain(){try{const u=new URL(input.value);domain.textContent=['http:','https:'].includes(u.protocol)?`Domain: ${u.hostname}`:'';}catch{domain.textContent='';}}
function renderResult(result){resultBox.hidden=false;resultBox.dataset.verdict=result.final_verdict.toLowerCase();verdict.textContent=result.final_verdict;score.textContent=result.threat_score===null?'Risk score unavailable':`Risk score: ${result.threat_score.toFixed(1)} / 100`;reasons.replaceChildren();(result.indicators.length?result.indicators:['No additional indicators were returned.']).forEach(text=>{const li=document.createElement('li');li.textContent=text;reasons.appendChild(li);});limitation.textContent=result.limitations[0]||'Use this result as one security signal, not an absolute guarantee.';}
async function loadActiveTab(){try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(tab?.url){const u=new URL(tab.url);if(['http:','https:'].includes(u.protocol)){input.value=tab.url;updateDomain();setStatus('URL detected. Review it, then choose Check URL.','ready');return;}}setStatus('This browser page cannot be checked. Enter an http(s) URL manually.','invalid');}catch{setStatus('Enter an http(s) URL to check.','idle');}}
button.addEventListener('click',async()=>{resultBox.hidden=true;let sanitized;try{sanitized=window.CyberSentinelAPI.sanitizeUrlForScan(input.value.trim());}catch(e){setStatus(e.message,'invalid');return;}input.value=sanitized;updateDomain();button.disabled=true;button.textContent='Checking…';setStatus('Sending the displayed URL to CyberSentinel for analysis.','scanning');try{const {result}=await window.CyberSentinelAPI.analyzeURL(sanitized);renderResult(result);setStatus('Check complete.','complete');await chrome.storage.local.set({lastScan:{domain:new URL(sanitized).hostname,verdict:result.final_verdict,at:new Date().toISOString()}});}catch(e){const msg=e.message==='RATE_LIMIT'?'Rate limit reached. Try again later.':e.message==='UNAVAILABLE'?'CyberSentinel is temporarily unavailable.':e.name==='AbortError'?'The check timed out. Try again.':'The URL could not be checked. Try again later.';setStatus(msg,'error');}finally{button.disabled=false;button.textContent='Check URL';}});
input.addEventListener('input',()=>{updateDomain();setStatus('Review the URL, then choose Check URL.','ready');});
document.addEventListener('DOMContentLoaded',loadActiveTab);
