import { useEffect,useState } from 'react';
import { Upload, RefreshCw, XCircle, Download } from 'lucide-react';
import { createBulkJob,getBulkJob,listBulkJobs,cancelBulkJob,downloadBulkResults } from '../services/api';
import SEO from '../components/SEO';
export default function BulkScanPage(){
 const [file,setFile]=useState(null),[jobs,setJobs]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=async()=>{try{const data=await listBulkJobs();setJobs(data.jobs||[]);if(selected){const detail=await getBulkJob(selected.job.id);setSelected(detail);}}catch(e){setError(e.message)}};
 useEffect(()=>{refresh();const id=setInterval(refresh,3000);return()=>clearInterval(id)},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const submit=async()=>{if(!file)return setError('Choose a CSV file first.');setBusy(true);setError('');try{const data=await createBulkJob(file);setSelected(data);setFile(null);await refresh();}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <main className="min-h-screen bg-slate-50 px-4 py-10"><SEO title="Bulk URL Scan — CyberSentinel" path="/bulk" noindex/><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-bold">Bulk URL scan</h1><p className="mt-2 text-slate-600">Authenticated asynchronous scanning. CSV must contain a <code>url</code> column. Jobs continue after you leave this page.</p>
 <section className="mt-6 rounded-xl border bg-white p-6"><input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><button disabled={!file||busy} onClick={submit} className="ml-3 rounded-lg bg-blue-700 px-4 py-2 text-white disabled:opacity-50"><Upload className="mr-2 inline h-4 w-4"/>{busy?'Uploading…':'Start job'}</button>{error&&<p className="mt-3 text-red-700">{error}</p>}</section>
 <section className="mt-6 rounded-xl border bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Your jobs</h2><button onClick={refresh}><RefreshCw className="h-5 w-5"/></button></div><div className="mt-4 space-y-3">{jobs.map(j=><button key={j.id} onClick={async()=>setSelected(await getBulkJob(j.id))} className="block w-full rounded-lg border p-3 text-left"><strong>{j.status}</strong> — {j.processed}/{j.total} ({j.progress_percent}%) <span className="text-slate-500">{j.id}</span></button>)}</div></section>
 {selected&&<section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Job {selected.job.id}</h2><p className="mt-2">{selected.job.status}: {selected.job.processed}/{selected.job.total}; successful {selected.job.successful}; failed {selected.job.failed}</p><div className="mt-3 flex gap-3">{['QUEUED','RUNNING','CANCELLING'].includes(selected.job.status)&&<button onClick={async()=>{await cancelBulkJob(selected.job.id);await refresh()}} className="rounded bg-red-700 px-3 py-2 text-white"><XCircle className="mr-2 inline h-4 w-4"/>Cancel</button>}{['COMPLETED','PARTIALLY_COMPLETED','CANCELLED'].includes(selected.job.status)&&<button onClick={()=>downloadBulkResults(selected.job.id)} className="rounded bg-slate-800 px-3 py-2 text-white"><Download className="mr-2 inline h-4 w-4"/>Download CSV</button>}</div><div className="mt-4 max-h-80 overflow-auto">{(selected.results||[]).map(r=><div key={r.row} className="border-t py-2 text-sm">Row {r.row}: {r.url} — {r.status} {r.verdict||''}</div>)}</div></section>}
 </div></main>}
