import { useEffect, useState } from 'react';
import { createFileScan, getFileScanCapabilities, listFileScans } from '../services/api';

export default function FileScanPage(){
 const [caps,setCaps]=useState(null),[file,setFile]=useState(null),[consent,setConsent]=useState(false),[jobs,setJobs]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=async()=>{try{setJobs((await listFileScans()).jobs||[])}catch{/* auth interceptor handles errors */}};
 useEffect(()=>{getFileScanCapabilities().then(setCaps).catch(e=>setError(e.message));refresh();const t=setInterval(refresh,3000);return()=>clearInterval(t)},[]);
 const submit=async(e)=>{e.preventDefault();setError('');if(!file||!consent)return setError('Choose a file and acknowledge consent.');setBusy(true);try{await createFileScan(file,true);setFile(null);setConsent(false);e.target.reset();await refresh()}catch(err){setError(err.message)}finally{setBusy(false)}};
 const verdict=(v)=>({CLEAN_CHECKS_COMPLETED:'Clean according to completed checks',THREAT_DETECTED:'Threat detected',SUSPICIOUS_INDICATORS:'Suspicious indicators detected',UNABLE_TO_COMPLETE:'Unable to complete analysis'}[v]||v||'Pending');
 return <main className="mx-auto max-w-5xl px-4 py-10"><h1 className="text-3xl font-bold">File & HTML Analysis</h1><p className="mt-2 text-gray-600">Files are scanned as untrusted data. CyberSentinel never executes uploaded files or HTML/JavaScript.</p>
 <section className="mt-6 rounded-xl border bg-white p-6"><p className="text-sm text-gray-600">Supported: {caps?.allowed_types?.join(', ')||'loading…'} · Maximum: {caps?`${Math.round(caps.max_bytes/1024/1024)} MB`:'…'} · Archives are not supported.</p>
 <form onSubmit={submit} className="mt-4 space-y-4"><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)} className="block w-full rounded border p-3"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I consent to upload this file for malware/static analysis. The original is deleted immediately after analysis; scan metadata/results may be retained for the configured retention period.</span></label><button disabled={busy||!caps?.enabled} className="rounded bg-blue-700 px-4 py-2 font-medium text-white disabled:opacity-50">{busy?'Uploading…':caps?.enabled?'Analyze file':'File analysis disabled'}</button>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</form></section>
 <section className="mt-8"><h2 className="text-xl font-semibold">Recent scans</h2><div className="mt-3 space-y-3">{jobs.map(j=><article key={j.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{j.file_name}</strong><span>{j.status}</span></div><p className="mt-1 text-sm">{verdict(j.verdict)}</p>{j.malware_status==='clean'&&<p className="mt-1 text-xs text-gray-500">ClamAV found no known malware in this scan. This is not a guarantee that the file is safe.</p>}{j.indicators?.length>0&&<ul className="mt-2 list-disc pl-5 text-sm">{j.indicators.map((x,i)=><li key={`${x.code}-${i}`}>{x.code.replaceAll('_',' ')} ({x.severity})</li>)}</ul>}{j.error_code&&<p className="mt-1 text-sm text-amber-700">Analysis could not complete: {j.error_code.replaceAll('_',' ')}</p>}</article>)}</div></section></main>
}
