import { useState } from 'react';
import { AlertTriangle, CheckCircle, Loader2, Shield, XCircle } from 'lucide-react';
import { analyzeURL } from '../services/api';

const style = { Safe: 'border-emerald-300 bg-emerald-50 text-emerald-900', Suspicious: 'border-amber-300 bg-amber-50 text-amber-900', Dangerous: 'border-red-300 bg-red-50 text-red-900', Unknown: 'border-slate-300 bg-slate-50 text-slate-900' };
const icons = { Safe: CheckCircle, Suspicious: AlertTriangle, Dangerous: XCircle, Unknown: Shield };

export default function ScannerPage() {
  const [url, setUrl] = useState(''); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function scan(event) {
    event.preventDefault(); setError(''); setResult(null);
    if (!/^https?:\/\//i.test(url.trim())) return setError('Enter a complete HTTP or HTTPS URL, for example https://example.com.');
    setLoading(true); try { setResult(await analyzeURL(url.trim())); } catch (err) { setError(err.response?.data?.error || err.message || 'The scan could not be completed. Please try again.'); } finally { setLoading(false); }
  }
  const verdict = result?.final_verdict || 'Unknown'; const Icon = icons[verdict] || Shield;
  return <main className="min-h-screen bg-slate-50 px-4 py-12"><section className="mx-auto max-w-3xl text-center"><Shield className="mx-auto mb-4 h-12 w-12 text-blue-700"/><h1 className="text-4xl font-bold text-slate-950">Check a suspicious link safely</h1><p className="mx-auto mt-4 max-w-2xl text-slate-600">CyberSentinel analyses the URL itself and optional reputation evidence. It does not open the submitted webpage.</p></section><section className="mx-auto mt-10 max-w-3xl rounded-2xl bg-white p-6 shadow-sm"><form onSubmit={scan} noValidate><label htmlFor="scan-url" className="block text-sm font-semibold text-slate-800">Website URL</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><input id="scan-url" type="url" inputMode="url" autoComplete="off" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" aria-describedby="scan-help scan-error" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-4 py-3 focus:border-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-200" disabled={loading}/><button className="rounded-lg bg-blue-700 px-6 py-3 font-semibold text-white disabled:bg-slate-400" disabled={loading}>{loading ? <span className="flex items-center justify-center gap-2"><Loader2 className="h-5 w-5 animate-spin"/>Checking</span> : 'Check link'}</button></div><p id="scan-help" className="mt-3 text-sm text-slate-600">Do not paste passwords, tokens, or private links. Results are risk indicators, not guarantees.</p>{error && <p id="scan-error" role="alert" className="mt-3 text-sm font-medium text-red-700">{error}</p>}</form></section>{result && <section aria-live="polite" className={`mx-auto mt-6 max-w-3xl rounded-2xl border p-6 ${style[verdict] || style.Unknown}`}><div className="flex gap-4"><Icon className="h-8 w-8 shrink-0"/><div><h2 className="text-2xl font-bold">{verdict}</h2><p className="mt-1">{typeof result.threat_score === 'number' ? `Risk score: ${result.threat_score}/100` : 'A reliable risk score is unavailable.'}</p><p className="mt-2 text-sm">Confidence: {result.confidence || 'unavailable'}</p></div></div>{result.indicators?.length > 0 && <ul className="mt-5 list-disc space-y-1 pl-5 text-sm">{result.indicators.map((item,i)=><li key={i}>{item}</li>)}</ul>}<div className="mt-5 border-t border-current/20 pt-4"><h3 className="font-semibold">What to do next</h3><ul className="mt-2 list-disc pl-5 text-sm">{(result.recommendations || ['Treat unknown links with caution.']).map((item,i)=><li key={i}>{item}</li>)}</ul></div></section>}</main>;
}
